====== Array Creation ======

In [34]:
#importing NumPy into your project
import numpy as np

# creating an one dimensional ndarray
x = np.array([10, 27, 34])
print (x)

[10 27 34]


In [10]:
# creating a two-dimensional ndarray
points = np.array([[11, 28, 9], [56, 38, 91], [33,87,36], [87,8,4]])
print (points)

[[11 28  9]
 [56 38 91]
 [33 87 36]
 [87  8  4]]


In [11]:
#creating a one dimensional array, whilst specifying the data type
y = np.array([10, 27, 34], dtype=np.float64)
print (y)

[10. 27. 34.]


In [12]:
# create an array with ones
a = np.ones((4,3), dtype=np.int16)
print (a)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [15]:
# create an array with random numbers
r = np.random.random([2,3])
print (r)

[[0.48746158 0.93214926 0.1450121 ]
 [0.69303901 0.43758922 0.62645661]]


In [17]:
# use the arange function to create a sequence of numbers
sequence1 = np.arange(0, 9, 3)
print (sequence1)

[0 3 6]


In [19]:
# these arange statements achieve identical results.
sequence2 = np.arange(5)
sequence3 = np.arange(0,5,1)
print (sequence2)
print (sequence3)

[0 1 2 3 4]
[0 1 2 3 4]


In [20]:
# the linspace function can also be used to obtain a sequence
sequence4 = np.linspace(0, 9, 3)
print (sequence4)

[0.  4.5 9. ]


====== Arithmetic Operations ======

In [23]:
# Elementwise arithmetic operations can be performed on ndarrays
array1 = np.array([[1,2,3], [2, 3, 4]])
array2 = np.array([[3,4,5], [4, 5, 6]])

Sum = array1 + array2
Difference = array1 - array2
Product = array1 * array2
Division = array1 / array2

print (Sum)
print (Difference)
print (Product)
print (Division)


[[ 4  6  8]
 [ 6  8 10]]
[[-2 -2 -2]
 [-2 -2 -2]]
[[ 3  8 15]
 [ 8 15 24]]
[[0.33333333 0.5        0.6       ]
 [0.5        0.6        0.66666667]]


In [33]:
# in-place elementwise arithmetic operations
array1 = np.array([1,2,3], dtype=np.float64)
array2 = np.array([3,4,5], dtype=np.float64)
array3 = np.array([4,5,6], dtype=np.float64)
array4 = np.array([5,6,7], dtype=np.float64)

# in-place arithmetic and can be performed using arrays of the same size
array1 += np.array([10,10,10], dtype=np.float64)
array2 -= np.array([10,10,10], dtype=np.float64)
array3 *= np.array([10,10,10], dtype=np.float64)
array4 /= np.array([10,10,10], dtype=np.float64)

# in-place arithmetic can be performed using a scalar value
array1 += 100.0
array2 -= 100.0
array3 *= 100.0
array4 /= 100.0

print (array1)
print (array2)
print (array3)
print (array4)


[111. 112. 113.]
[-107. -106. -105.]
[4000. 5000. 6000.]
[0.005 0.006 0.007]


In [37]:
# the exponent operator
array1 = np.arange(4, dtype=np.float64)
array1 **= 4
print (array1)

[ 0.  1. 16. 81.]


====== Comparison Operators ======

In [40]:
array1 = np.array([1,4,5])
array2 = np.array([3,2,5])

# less than
print (array1 < array2)

# less than equal to
print (array1 <= array2)

# greater than
print (array1 > array2)

# greater than equal to
print (array1 >= array2)

# equal to
print (array1 == array2)

# not equal to
print (array1 != array2)

[ True False False]
[ True False  True]
[False  True False]
[False  True  True]
[False False  True]
[ True  True False]


====== Matrix/Vector Operations ======

In [41]:
array1 = np.array([1,4,5], dtype=np.float_)
array2 = np.array([3,2,5], dtype=np.float_)

# inner (dot product)
print (np.inner(array1, array2))

# outer product
print (np.outer(array1, array2))

# cross product
print (np.cross(array1, array2))


36.0
[[ 3.  2.  5.]
 [12.  8. 20.]
 [15. 10. 25.]]
[ 10.  10. -10.]


====== Indexing and Slicing ======

In [54]:
# create a one-dimensional array with 10 elements
array1 = np.linspace(0, 9, 10)
print (array1)

# get the third element. Indexes are zero-based.
print (array1[3])

# extracts elements 2 , 3, 4 into a sub array
print (array1[2:5])

#extract first 6 elements of the array (elements 0 to 5)
print (array1[:6])

# extract elements 5 onwards
print(array1[5:])

# extract every alternate element, step value is specified as 2
print (array1[::2])

# reverse all the elements in array1
print (array1[::-1])

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
3.0
[2. 3. 4.]
[0. 1. 2. 3. 4. 5.]
[5. 6. 7. 8. 9.]
[0. 2. 4. 6. 8.]
[9. 8. 7. 6. 5. 4. 3. 2. 1. 0.]


In [67]:
# create a two-dimensional array with 12 elements
array1 = np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
print (array1)

# get the element in the second row, third column. Indexes are zero-based.
print (array1[1,2])

# get all the elements in the first column
print (array1[:,0])

#get all the elements in the first row
print (array1[0,:])

# get a sub 2-dimensional array
print (array1[:3, :2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
[1 5 9]
[1 2 3 4]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
